config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :users do
    collection do
      get :details
    end
  end

  resources :recipes

  resources :meals

  resources :home do
    collection do
      get :about
      get :faqs
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  root :to => 'home#index'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_one :meal

  # scope :dairy, where(:diets => "dairy free")
  # scope :shellfish, where(:diets => "shellfish allergy")
  # scope :veg, where(:diets => "vegan") //need to update scope to include like statement for vegan OR vegetarian
  # scope :nut, where(:diets => "nut allergy")
  # scope :gluten, where(:diets => "gluten free")
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :only => [:new, :edit, :destroy] do
    (flash.alert = "You are not authorized to access that page.";
    redirect_to '/') unless admin?
  end

  def index
    @recipes = Recipe.all
    @user = current_user
    @meal = @user.meals.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :imageUrl, :calories, :protein, :fat, :carbohydrates, :instructions, :diets, :ingredients)
  end
end

app/views/recipes/_form.html.erb
<%= render 'layouts/errors', :object => @recipe %>

<%= form_for @recipe do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image_link %>
    <%= f.text_field :imageUrl, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :calories %>
    <%= f.number_field :calories, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :protein %>
    <%= f.number_field :protein, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fat %>
    <%= f.number_field :fat, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :carbohydrates %>
    <%= f.number_field :carbohydrates, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :instructions %>
    <%= f.text_area :instructions, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-default'%>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h3>Edit <%= @recipe.title %></h3>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h2>Recipes</h2>
<% @recipes.each do |recipe| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%=link_to image_tag('recipecard.png', alt:'recipe icon', size: '50x35'), recipe_path(recipe.id) %>  <%= link_to recipe.title, recipe_path(recipe.id) %></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-6">
        <div class="recipe-image">
          <%= image_tag(recipe.imageUrl, size: "250x250",  alt:'recipe image', class:'img-responsive') %>
          <br>
        </div>
      </div>

      <div class="col-md-6">
        <div class="well">
          Cal: <%= recipe.calories %> | Protein: <%= recipe.protein %> g | Fat: <%= recipe.fat %> g | Carbs: <%= recipe.carbohydrates %> g
          <br>
          <% recipe.diets.each do |diet| %>
            <% if diet === "dairy free" %>
              <%= image_tag("milk-icon.png", size: "30x30",  alt:'milk-icon', id:'milk-icon') %>
            <% elsif diet === "gluten free" %>
              <%= image_tag("wheat-icon.png", size: "30x30",  alt:'wheat-icon', id:'wheat-icon') %>
            <% elsif diet === "vegan" || diet === "vegetarian" %>
              <%= image_tag("vegan-icon.png", size: "30x30",  alt:'vegan-icon', id:'vegan-icon') %>
            <% elsif diet === "nut allergy" %>
              <%= image_tag("nut-icon.png", size: "30x30",  alt:'nut-icon', id:'nut-icon') %>
            <% elsif diet === "shellfish allergy" %>
              <%= image_tag("shellfish-icon.png", size: "30x30",  alt:'shellfish-icon', id:'shellfish-icon') %>
            <% end %>
          <% end %>
        </div>
        <%= form_for @meal do |f| %>
        <%= f.hidden_field :recipe_id, value: recipe.id %>
        <div class="form-group">
          <%= f.select :category, options_for_select([
            ['Breakfast', 'Breakfast'],
            ['Lunch', 'Lunch'],
            ['Dinner', 'Dinner']
            ]), {}, {class: 'form-control'} %>
        </div>
        <div class="form-group">
          <%= f.label :date %>
          <%= f.date_field :start_time, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Add Meal", class:'btn btn-default' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h3>Add New Recipe</h3>
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><%= @recipe.title %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <div class="recipe-image">
        <%= image_tag(@recipe.imageUrl, size: "250x250",  alt:'recipe image', id:'recipeImg', class:'img-responsive') %>
      </div>
      <br>
    </div>
    <div class="col-md-6">
      <div class="well">
        Cal: <%= @recipe.calories %> | Protein: <%= @recipe.protein %> g | Fat: <%= @recipe.fat %> g | Carbs: <%= @recipe.carbohydrates %> g
        <br>
        <% @recipe.diets.each do |diet| %>
          <% if diet === "dairy free" %>
            <%= image_tag("milk-icon.png", size: "30x30",  alt:'milk-icon', id:'milk-icon') %>
          <% elsif diet === "gluten free" %>
            <%= image_tag("wheat-icon.png", size: "30x30",  alt:'wheat-icon', id:'wheat-icon') %>
          <% elsif diet === "vegan" || diet === "vegetarian" %>
            <%= image_tag("vegan-icon.png", size: "30x30",  alt:'vegan-icon', id:'vegan-icon') %>
          <% elsif diet === "nut allergy" %>
            <%= image_tag("nut-icon.png", size: "30x30",  alt:'nut-icon', id:'nut-icon') %>
          <% elsif diet === "shellfish allergy" %>
            <%= image_tag("shellfish-icon.png", size: "30x30",  alt:'shellfish-icon', id:'shellfish-icon') %>
          <% end %>
        <% end %>
      </div>

      <h4>Ingredients</h4>
      <ul>
        <% @recipe.ingredients.uniq.each do |ingredient| %>
          <li><%= ingredient %></li>
        <% end %>
      </ul>

      <h4>Instructions</h4>
      <ul>
        <% @recipe.instructions.each do |step| %>
          <li><%= step %></li>
        <% end %>
      </ul>

      <% if admin? %>
        <div class="well">
          <%= link_to "Edit", edit_recipe_path(@recipe) %> | <%= link_to "Delete", recipe_path(@recipe), :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>