config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :users do
    collection do
      get :details
    end
  end

  resources :recipes

  resources :meals

  resources :home do
    collection do
      get :about
      get :faqs
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  root :to => 'home#index'
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe

  delegate :title, :calories, :fat, :carbohydrates, :protein, to: :meal
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @user = current_user
    @meals = @user.meals
  end

  def create
    @user = current_user
    @meal = @user.meals.create!(meal_params)
    redirect_to user_path(@user)
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to user_path(@meal.user)
  end

  private
  def meal_params
    params.require(:meal).permit(:category, :start_time, :recipe_id)
  end
end

app/views/meals/_day_calendar.html.erb
<div class="day_calendar">
  <%= calendar(number_of_days: 1, events: @meals) do |date, meals| %>
    <h4><%= date %></h4>

    <% total_calories = 0 %><% total_protein = 0 %><% total_fat = 0 %><% total_carbohydrates = 0 %>
    <% meals.each do |meal| %>
      <div class="cal-item">
        <% if meal.category === "Breakfast" %>
          <%= image_tag("Bicon.png", size: "20x20",  alt:'Bicon', id:'Bicon') %>
        <% elsif meal.category === "Lunch" %>
          <%= image_tag("Licon.png", size: "20x20",  alt:'Licon', id:'Licon') %>
        <% elsif meal.category === "Dinner" %>
          <%= image_tag("Dicon.png", size: "20x20",  alt:'Dicon', id:'Dicon') %>
        <% elsif meal.category === "Other" %>
          <%= image_tag("Oicon.png", size: "20x20",  alt:'Oicon', id:'Oicon') %>
        <% end %><%= link_to meal.recipe.title, recipe_path(meal.recipe_id) %><%= link_to " x", meal_path(meal), class:'remove', :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </div>
      <% total_calories = total_calories + meal.recipe.calories %>
      <% total_protein = total_protein + meal.recipe.protein %>
      <% total_fat = total_fat + meal.recipe.fat %>
      <% total_carbohydrates = total_carbohydrates + meal.recipe.carbohydrates %>
    <% end %>
    <% if meals.any? %>
      <div class="well">
        <h4>Total Macros</h4>
        Cal: <%= total_calories %> | Protein: <%= total_protein %> g | Fat: <%= total_fat %> g | Carbs: <%= total_carbohydrates %> g
      </div>
    <% end %>
  <% end %>
</div>

app/views/meals/_month_calendar.html.erb
<div class="month_calendar">
  <%= month_calendar events: @meals do |date, meals| %>
    <%= date %>

    <% total_calories = 0 %><% total_protein = 0 %><% total_fat = 0 %><% total_carbohydrates = 0 %>
    <% meals.each do |meal| %>
      <div class="cal-item">
        <% if meal.category === "Breakfast" %>
          <%= image_tag("Bicon.png", size: "20x20",  alt:'Bicon', id:'Bicon') %>
        <% elsif meal.category === "Lunch" %>
          <%= image_tag("Licon.png", size: "20x20",  alt:'Licon', id:'Licon') %>
        <% elsif meal.category === "Dinner" %>
          <%= image_tag("Dicon.png", size: "20x20",  alt:'Dicon', id:'Dicon') %>
        <% elsif meal.category === "Other" %>
          <%= image_tag("Oicon.png", size: "20x20",  alt:'Oicon', id:'Oicon') %>
        <% end %><%= link_to meal.recipe.title, recipe_path(meal.recipe_id) %><%= link_to " x", meal_path(meal), class:'remove', :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </div>
      <% total_calories = total_calories + meal.recipe.calories %>
      <% total_protein = total_protein + meal.recipe.protein %>
      <% total_fat = total_fat + meal.recipe.fat %>
      <% total_carbohydrates = total_carbohydrates + meal.recipe.carbohydrates %>
    <% end %>

    <% if meals.any? %>
      <div class="well">
        <strong>Total Macros</strong><br>
        Cal: <%= total_calories %><br>
        Protein: <%= total_protein %> g<br>
        Fat: <%= total_fat %> g<br>
        Carbs: <%= total_carbohydrates %> g
      </div>
    <% end %>
  <% end %>
</div>

app/views/meals/_week_calendar.html.erb
<div class="week_calendar">
  <%= week_calendar events: @meals do |date, meals| %>
    <h5><%= date %></h5>

    <% total_calories = 0 %><% total_protein = 0 %><% total_fat = 0 %><% total_carbohydrates = 0 %>
    <% meals.each do |meal| %>
      <div class="cal-item">
        <% if meal.category === "Breakfast" %>
          <%= image_tag("Bicon.png", size: "20x20",  alt:'Bicon', id:'Bicon') %>
        <% elsif meal.category === "Lunch" %>
          <%= image_tag("Licon.png", size: "20x20",  alt:'Licon', id:'Licon') %>
        <% elsif meal.category === "Dinner" %>
          <%= image_tag("Dicon.png", size: "20x20",  alt:'Dicon', id:'Dicon') %>
        <% elsif meal.category === "Other" %>
          <%= image_tag("Oicon.png", size: "20x20",  alt:'Oicon', id:'Oicon') %>
        <% end %><%= link_to meal.recipe.title, recipe_path(meal.recipe_id) %><%= link_to " x", meal_path(meal), class:'remove', :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </div>
      <% total_calories = total_calories + meal.recipe.calories %>
      <% total_protein = total_protein + meal.recipe.protein %>
      <% total_fat = total_fat + meal.recipe.fat %>
      <% total_carbohydrates = total_carbohydrates + meal.recipe.carbohydrates %>
    <% end %>

    <% if meals.any? %>
      <div class="well">
        <strong>Total Macros</strong><br>
        Cal: <%= total_calories %><br>
        Protein: <%= total_protein %> g<br>
        Fat: <%= total_fat %> g<br>
        Carbs: <%= total_carbohydrates %> g
      </div>
    <% end %>
  <% end %>
</div>

app/views/meals/index.html.erb
<h2>Meal Plans</h2>
<nav class="nav navbar">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="#day" id="day-link">Day</a>
    </li>
    <li class="nav-item">
      <a href="#week" id="week-link">Week</a>
    </li>
    <li class="nav-item">
      <a href="#month" id="month-link">Month</a>
    </li>
    <li class="nav-item active pull-right">
      <%= link_to 'Print', meals_path, :onclick => 'window.print();return false;', class:"pull-right"%>
    </li>
  </ul>
</nav>

<div class="day_calendar" id="day">
  <%= calendar(number_of_days: 1, events: @meals) do |date, meals| %>
    <h4><%= date %></h4>

    <% total_calories = 0 %><% total_protein = 0 %><% total_fat = 0 %><% total_carbohydrates = 0 %>
    <% meals.each do |meal| %>
      <div class="cal-item">
        <% if meal.category === "Breakfast" %>
          <%= image_tag("Bicon.png", size: "20x20",  alt:'Bicon', id:'Bicon') %>
        <% elsif meal.category === "Lunch" %>
          <%= image_tag("Licon.png", size: "20x20",  alt:'Licon', id:'Licon') %>
        <% elsif meal.category === "Dinner" %>
          <%= image_tag("Dicon.png", size: "20x20",  alt:'Dicon', id:'Dicon') %>
        <% elsif meal.category === "Other" %>
          <%= image_tag("Oicon.png", size: "20x20",  alt:'Oicon', id:'Oicon') %>
        <% end %><%= link_to meal.recipe.title, recipe_path(meal.recipe_id) %><%= link_to " x", meal_path(meal), class:'remove', :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </div>
      <% total_calories = total_calories + meal.recipe.calories %>
      <% total_protein = total_protein + meal.recipe.protein %>
      <% total_fat = total_fat + meal.recipe.fat %>
      <% total_carbohydrates = total_carbohydrates + meal.recipe.carbohydrates %>
    <% end %>
    <% if meals.any? %>
      <div class="well">
        <h4>Total Macros</h4>
        Cal: <%= total_calories %> | Protein: <%= total_protein %> g | Fat: <%= total_fat %> g | Carbs: <%= total_carbohydrates %> g
      </div>
    <% end %>
  <% end %>
</div>

<div class="week_calendar" id="week">
  <%= week_calendar(events: @meals) do |date, meals| %>
    <h5><%= date %></h5>

    <% total_calories = 0 %><% total_protein = 0 %><% total_fat = 0 %><% total_carbohydrates = 0 %>
    <% meals.each do |meal| %>
      <div class="cal-item">
        <% if meal.category === "Breakfast" %>
          <%= image_tag("Bicon.png", size: "20x20",  alt:'Bicon', id:'Bicon') %>
        <% elsif meal.category === "Lunch" %>
          <%= image_tag("Licon.png", size: "20x20",  alt:'Licon', id:'Licon') %>
        <% elsif meal.category === "Dinner" %>
          <%= image_tag("Dicon.png", size: "20x20",  alt:'Dicon', id:'Dicon') %>
        <% elsif meal.category === "Other" %>
          <%= image_tag("Oicon.png", size: "20x20",  alt:'Oicon', id:'Oicon') %>
        <% end %><%= link_to meal.recipe.title, recipe_path(meal.recipe_id) %><%= link_to " x", meal_path(meal), class:'remove', :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </div>
      <% total_calories = total_calories + meal.recipe.calories %>
      <% total_protein = total_protein + meal.recipe.protein %>
      <% total_fat = total_fat + meal.recipe.fat %>
      <% total_carbohydrates = total_carbohydrates + meal.recipe.carbohydrates %>
    <% end %>

    <% if meals.any? %>
      <div class="well">
        <strong>Total Macros</strong><br>
        Cal: <%= total_calories %><br>
        Protein: <%= total_protein %> g<br>
        Fat: <%= total_fat %> g<br>
        Carbs: <%= total_carbohydrates %> g
      </div>
    <% end %>
  <% end %>
</div>


<div class="month_calendar" id="month">
  <%= month_calendar(events: @meals) do |date, meals| %>
    <%= date %>

    <% total_calories = 0 %><% total_protein = 0 %><% total_fat = 0 %><% total_carbohydrates = 0 %>
    <% meals.each do |meal| %>
      <div class="cal-item">
        <% if meal.category === "Breakfast" %>
          <%= image_tag("Bicon.png", size: "20x20",  alt:'Bicon', id:'Bicon') %>
        <% elsif meal.category === "Lunch" %>
          <%= image_tag("Licon.png", size: "20x20",  alt:'Licon', id:'Licon') %>
        <% elsif meal.category === "Dinner" %>
          <%= image_tag("Dicon.png", size: "20x20",  alt:'Dicon', id:'Dicon') %>
        <% elsif meal.category === "Other" %>
          <%= image_tag("Oicon.png", size: "20x20",  alt:'Oicon', id:'Oicon') %>
        <% end %><%= link_to meal.recipe.title, recipe_path(meal.recipe_id) %><%= link_to " x", meal_path(meal), class:'remove', :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </div>
      <% total_calories = total_calories + meal.recipe.calories %>
      <% total_protein = total_protein + meal.recipe.protein %>
      <% total_fat = total_fat + meal.recipe.fat %>
      <% total_carbohydrates = total_carbohydrates + meal.recipe.carbohydrates %>
    <% end %>

    <% if meals.any? %>
      <div class="well">
        <strong>Total Macros</strong><br>
        Cal: <%= total_calories %><br>
        Protein: <%= total_protein %> g<br>
        Fat: <%= total_fat %> g<br>
        Carbs: <%= total_carbohydrates %> g
      </div>
    <% end %>
  <% end %>
</div>