config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :users do
    collection do
      get :details
    end
  end

  resources :recipes

  resources :meals

  resources :home do
    collection do
      get :about
      get :faqs
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  root :to => 'home#index'
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <h4><em><%= value %></em></h4>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealThyme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Zilla+Slab" rel="stylesheet">
  </head>
  <%= render 'layouts/messages' %>
  <body>
    <div class="body">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <footer class="bottom-nav">
      <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to 'Home', '/', {class: "navbar-brand"} %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "#{current_user.email}'s Profile", user_path(current_user) %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
            <% end %>
            <li><%= link_to "About", about_home_index_path %></li>
            <li><%= link_to "FAQs", faqs_home_index_path %></li>
            <li><%= link_to "Contact", new_contact_path %></li>
          </ul>
        </div>
      </nav>
    </footer>
  </body>
</html>